# Generated by Django 4.1 on 2024-09-25 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('abstract', models.TextField()),
                ('pdf_url', models.URLField()),
                ('transformed', models.CharField(max_length=200000)),
            ],
            options={
                'db_table': 'paper_data',
            },
        ),
    ]
