# Generated by Django 4.1 on 2024-09-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('authors', models.CharField(max_length=100)),
                ('abstract', models.TextField()),
                ('url', models.URLField()),
                ('comments', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'paper_search',
            },
        ),
    ]
